### ISSUE TITLE
SIGSEGV in version 0.14 : support old rmapi zip file format and lack of .metadata files

### ISSUE THREAD

**Issue by qwert2003** [rorycl/rm2pdf#9] opened 2022-09-25 21:02 UTC
rm2pdf version 0.1.4:

```
> rm2pdf -v tst.zip outputtst_14.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x48f754]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
        /usr/lib/go-1.18/src/io/io.go:645 +0xd4
github.com/rorycl/rm2pdf/files.RMFiler({0x7ffce153a16a, 0x7}, {0x0, 0x0})
        /home/rory/src/go-rm2pdf/files/files.go:278 +0x3bd
github.com/rorycl/rm2pdf/rmpdf.RM2PDF({0x7ffce153a16a?, 0x1?}, {0x7ffce153a172, 0x10}, {0x0?, 0x200000003?}, {0x0, 0x0}, 0x1, {0x0, ...})
        /home/rory/src/go-rm2pdf/rmpdf/pdf.go:260 +0x9e
main.main()
        /home/rory/src/go-rm2pdf/main.go:63 +0x157
```

or (tst.zip extracted)

```
> rm2pdf -v ddae88d1-7514-43b6-b7de-dcdd18eeb69a outputdd_14.pdf   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x48f754]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
        /usr/lib/go-1.18/src/io/io.go:645 +0xd4
github.com/rorycl/rm2pdf/files.RMFiler({0x7fff7699314e, 0x24}, {0x0, 0x0})
        /home/rory/src/go-rm2pdf/files/files.go:278 +0x3bd
github.com/rorycl/rm2pdf/rmpdf.RM2PDF({0x7fff7699314e?, 0x1?}, {0x7fff76993173, 0xf}, {0x0?, 0x200000003?}, {0x0, 0x0}, 0x1, {0x0, ...})
        /home/rory/src/go-rm2pdf/rmpdf/pdf.go:260 +0x9e
main.main()
        /home/rory/src/go-rm2pdf/main.go:63 +0x157
```

rm2pdf version 0.1.3 did work:

```
> rm2pdf013 -v ddae88d1-7514-43b6-b7de-dcdd18eeb69a outputdd_13.pdf 
processing page 0 0 inserted false template true
 rm page 1 pdf page 1
orientation portrait
rmfile ddae88d1-7514-43b6-b7de-dcdd18eeb69a/0.rm
Beginning layer 1
Maximum coordinates : {X:379.57184 Y:133.96654}

```

Tested on OpenSuse Leap 15.3
```
go version
go version go1.19.1 linux/amd64
```

[tst.zip](https://github.com/rorycl/rm2pdf/files/9641793/tst.zip)

**Comment by rorycl** [comment] 2022-09-25 21:25
Thanks very much for the bug report @qwert2003.

Here is a dump of the output of the zip file fs.FS:
```
&files.RmFS{fs:(*zip.ReadCloser)(0xc000202770),fsPath:"/tmp/tst.zip",
rmfsType:0, filter:"", identifier:"ddae88d1-7514-43b6-b7de-dcdd18eeb69a",
contentPath:"ddae88d1-7514-43b6-b7de-dcdd18eeb69a.content",
content:(*zip.checksumReader)(0xc0001ca410), metadataPath:"", metadata:fs.File(nil),
pdfPath:"", pdf:fs.File(nil), pdfBytes:[]uint8(nil), pdfReader:io.ReadSeeker(nil),
templatePath:"embedded A4.pdf", template:(*embed.openFile)(0xc0002140c0),
templateBytes:[]uint8(nil), templateReader:(*embed.openFile)(0xc0002140c0), 
rmFiles:map[string]files.rmFileDesc{"ddae88d1-7514-43b6-b7de-dcdd18eeb69a/0":
files.rmFileDesc{rmPath:"ddae88d1-7514-43b6-b7de-dcdd18eeb69a/0.rm",
rm:(*zip.checksumReader)(0xc0001ca3c0),
metadataPath:"ddae88d1-7514-43b6-b7de-dcdd18eeb69a/0-metadata.json",
metadata:(*zip.checksumReader)(0xc0001ca370)}}}
```

The issue is that there is no metadata file in that file bundle. I'm not sure I've seen that before. However the data from the metadata (Version, VisibleName and LastModified) aren't really used anywhere in rm2pdf at the moment, so I'll make the metadata file optional again in a patch, which I should be able to do soon.

Would you mind if I add your test zip to the project testfiles? Thanks again for the bug report.

**Comment by qwert2003** [comment] 2022-09-25 22:15
Thanks for the quick answer.

Until 2021 the rmapi zip did not contain the metadata file. Current versions do include the file indeed. To be honest, the zip I have used for testing was not created by rmapi but by [drawj2d](https://drawj2d.sourceforge.io/). Rmapi still does not require the metadata file to upload notebooks (therefore there was no pressure to adapt drawj2d). Anyway I would appreciate if rm2pdf did not require the metadata file.

There might be another issue. When I upload tst.zip by rmapi and download it again (thus the metadata file exists) and run rm2pdf I get an empty pdf.
```
> rmapi put tst.zip

> rmapi
[/]>mv tst tst2
[/]>get tst2

> rm2pdf -v tst2.zip out-tst2-rm2pdf014.pdf
processing page 0 0 inserted false template true
embedded A4.pdf rm page 1 pdf page 1
orientation portrait
no rm file for page 1 ...skipping
```
I also see this behaviour for rmapi zip files of notebooks created on the rM device only (drawj2d not involved).
Using version 0.1.3 works.

**Comment by rorycl** [comment] 2022-09-26 07:08
Thanks for the further info @qwert2003. It looks like there might be two bugs:

1. failing due to no metadata (to support pre-2021 rmapi zip bundles)
2. possible page count issues with rm files

I refactored the first when adding abstract filesystem support in 0.1.4, and I also tweaked how pages are processed due to possibly missing rm pages. I'll start looking at these later today.

**Comment by rorycl** [comment] 2022-09-26 19:27
Hi @qwert2003. Apart from letting me know if you are ok if I add your `tst.zip` to the project testfiles (used for testing), please let me know if the patched version of `rm2pdf` attached here works for you. 

The binary has the following support for older rmapi zip bundles:
* metadata : missing metadata files are ignored
* rm file naming: older versions of rmapi zips used a 0-indexed filename rather than the actual .rm file uuid

I'd be grateful if you could confirm if the attached works for you.

Thanks
Rory

[rm2pdf.zip](https://github.com/rorycl/rm2pdf/files/9649107/rm2pdf.zip)

**Comment by qwert2003** [comment] 2022-09-26 22:33
Hello @rorycl. Please feel free to add tst.zip to the project test files.

The rm2pdf binary attached works for the cases I have tested before. Thanks!

Doing some more tests on backupped "real" notebooks I have noticed that prior to 2022 sometimes the pageuuid-metadata.json file is missing (for the last page actually). This is not related to rmapi, it seems the rM tablet did just not create that page metadata file in some circumstances. Could you ignore missing pageuuid-metadata.json files too?

**Comment by rorycl** [comment] 2022-09-27 07:09
Hi @qwert2003; thanks for the note about tst.zip -- I've gone ahead and added it to the test files. Thank you.

I've pushed out release v.0.1.5 based on the previous two items. I've made [issue 10](https://github.com/rorycl/rm2pdf/issues/10) for the missing rm metadata files. If you could provide an rm bundle, perhaps with more than one page, showing this issue that would be great. Please post it under issue 10, I'm closing this issue, assuming all is ok with it.

Thanks very much. Rory.

**Closed by rorycl** 2022-09-27 07:09 UTC
Labels: bug
